HIGH_MAG=20
LOW_MAG=5
PATCH_SIZE=256

LOW_DIR=/work/u6658716/TCGA-LUAD/CLAM/PATCHES/New_LUAD/tiles-${LOW_MAG}x-s${PATCH_SIZE}
HIGH_DIR=/work/u6658716/TCGA-LUAD/CLAM/PATCHES/New_LUAD/tiles-${LOW_MAG}x-s${PATCH_SIZE}/tiles-${HIGH_MAG}x-s${PATCH_SIZE}

TIMESHIMP=$(date +"%Y%m%d%H%M")
LOG_FILE=${TIMESHIMP}.log

cd /work/u6658716/TCGA-LUAD/DSCA/tools
python big_to_small_patching.py $LOW_DIR $HIGH_DIR $LOW_MAG $HIGH_MAG
